complete -c bl -x
complete -c bl -n '__fish_no_arguments' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_use_subcommand' -xa create -d 'create Backlog issue'
complete -c bl -n '__fish_seen_subcommand_from create' -s p -l project -xa '(bl resource list projects)' -d 'create issue on PROJECT'
complete -c bl -n '__fish_seen_subcommand_from create' -s I -l parent-issue -d 'issue parent issue'
complete -c bl -n '__fish_seen_subcommand_from create' -s s -l summary -d 'issue summary'
complete -c bl -n '__fish_seen_subcommand_from create' -s d -l description -d 'issue description'
complete -c bl -n '__fish_seen_subcommand_from create' -s S -l start-date -d 'issue start date'
complete -c bl -n '__fish_seen_subcommand_from create' -s D -l due-date -d 'issue due date'
complete -c bl -n '__fish_seen_subcommand_from create' -s t -l issue-type -xa '(bl resource list issueTypes)' -d 'issue type'
complete -c bl -n '__fish_seen_subcommand_from create' -s c -l category -xa '(bl resource list categories)' -d 'issue category'
complete -c bl -n '__fish_seen_subcommand_from create' -s v -l version -xa '(bl resource list versions)' -d 'issue version'
complete -c bl -n '__fish_seen_subcommand_from create' -s m -l milestone -xa '(bl resource list versions)' -d 'issue milestone'
complete -c bl -n '__fish_seen_subcommand_from create' -s P -l priority -xa '(bl resource list priorities)' -d 'issue priority'
complete -c bl -n '__fish_seen_subcommand_from create' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_use_subcommand' -xa update -d 'update Backlog issue'
complete -c bl -n '__fish_seen_subcommand_from update' -s i -l issue -d 'update ISSUE'
complete -c bl -n '__fish_seen_subcommand_from update' -s I -l parent-issue -d 'issue parent issue'
complete -c bl -n '__fish_seen_subcommand_from update' -s s -l summary -d 'issue summary'
complete -c bl -n '__fish_seen_subcommand_from update' -s d -l description -d 'issue description'
complete -c bl -n '__fish_seen_subcommand_from update' -s S -l start-date -d 'issue start date'
complete -c bl -n '__fish_seen_subcommand_from update' -s D -l due-date -d 'issue due date'
complete -c bl -n '__fish_seen_subcommand_from update' -s t -l issue-type -xa '(bl resource list issueTypes)' -d 'issue type'
complete -c bl -n '__fish_seen_subcommand_from update' -s c -l category -xa '(bl resource list categories)' -d 'issue category'
complete -c bl -n '__fish_seen_subcommand_from update' -s v -l version -xa '(bl resource list versions)' -d 'issue version'
complete -c bl -n '__fish_seen_subcommand_from update' -s m -l milestone -xa '(bl resource list versions)' -d 'issue milestone'
complete -c bl -n '__fish_seen_subcommand_from update' -s P -l priority -xa '(bl resource list priorities)' -d 'issue priority'
complete -c bl -n '__fish_seen_subcommand_from update' -s T -l status -xa '(bl resource list statuses)' -d 'issue status'
complete -c bl -n '__fish_seen_subcommand_from update' -s r -l resolution -xa '(bl resource list resolutions)' -d 'issue resolution'
complete -c bl -n '__fish_seen_subcommand_from update' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_use_subcommand' -xa resource -d 'manage Backlog resources'
complete -c bl -n '__fish_seen_subcommand_from resource; and not __fish_seen_subcommand_from sync list' -xa sync -d 'sync Backlog resources to caches'
complete -c bl -n '__fish_seen_subcommand_from resource; and __fish_seen_subcommand_from sync' -s p -l project -xa '(bl resource list projects)' -d 'create issue on PROJECT'
complete -c bl -n '__fish_seen_subcommand_from resource; and __fish_seen_subcommand_from sync' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_seen_subcommand_from resource; and not __fish_seen_subcommand_from sync list' -xa list -d 'list Backlog resources from caches'
complete -c bl -n '__fish_seen_subcommand_from resource; and __fish_seen_subcommand_from list' -s p -l project -xa '(bl resource list projects)' -d 'create issue on PROJECT'
complete -c bl -n '__fish_seen_subcommand_from resource; and __fish_seen_subcommand_from list' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_seen_subcommand_from resource; and __fish_seen_subcommand_from list' -xa 'projects issueTypes categories versions priorities statuses resolutions' -d 'resource_type'
complete -c bl -n '__fish_use_subcommand' -xa configure -d 'edit config'
complete -c bl -n '__fish_seen_subcommand_from completion' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_use_subcommand' -xa completion -d 'print evaluatable completion script'
complete -c bl -n '__fish_seen_subcommand_from completion' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_seen_subcommand_from completion' -xa 'bash fish' -d 'shell'
complete -c bl -n '__fish_use_subcommand' -xa help -d 'print usage and exit'
complete -c bl -n '__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from resource' -s h -l help -d 'print usage and exit'
complete -c bl -n '__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from resource' -xa create -d 'create Backlog issue'
complete -c bl -n '__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from resource' -xa update -d 'update Backlog issue'
complete -c bl -n '__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from resource' -xa resource -d 'manage Backlog resources'
complete -c bl -n '__fish_seen_subcommand_from help; and __fish_seen_subcommand_from resource' -xa sync -d 'sync Backlog resources to caches'
complete -c bl -n '__fish_seen_subcommand_from help; and __fish_seen_subcommand_from resource' -xa list -d 'list Backlog resources from caches'
complete -c bl -n '__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from resource' -xa completion -d 'print evaluatable completion script'
complete -c bl -n '__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from resource' -xa help -d 'print usage and exit'
